version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: chat_app_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: pgAdmin123
      POSTGRES_DB: chat_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./config/chat.dev.env

volumes:
  postgres_data:
